import Image from 'next/image';
import { Inter } from 'next/font/google';
import logo from '../public/logo.svg';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Eric — Home',
  description: 'Generated by create next app',
  openGraph: {
    title: ' asdfsadfg',
    description: 'The React Framework for the Web',
    url: 'https://nextjs.org',
    siteName: 'Next.js',
    images: [
      {
        url: 'https://nextjs.org/og.png',
        width: 800,
        height: 600,
      },
      {
        url: 'https://nextjs.org/og-alt.png',
        width: 1800,
        height: 1600,
        alt: 'My custom alt',
      },
    ],
    locale: 'en-US',
    type: 'website',
  },
};

export default function Home() {
  return (
    <>
      <header className="m-6">
        <Image src={logo} alt="" />
      </header>
      <div className="mx-auto my-32 h-full w-full max-w-5xl rounded-xl px-4">
        <h1 className="py-3 text-5xl font-bold antialiased">
          I'm Eric, I'm based in brazil. My <span className="text-gray-600">career </span>
          is revolving around software engineering / leading world-class{' '}
          <span className="text-gray-600">projects</span>.
        </h1>
      </div>
    </>
  );
}
