import Image from 'next/image';
import { Inter } from 'next/font/google';
import logo from '../public/logo.svg';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Eric — Home',
  description: 'Generated by create next app',
  openGraph: {
    title: ' asdfsadfg',
    description: 'The React Framework for the Web',
    url: 'https://nextjs.org',
    siteName: 'Next.js',
    images: [
      {
        url: 'https://nextjs.org/og.png',
        width: 800,
        height: 600,
      },
      {
        url: 'https://nextjs.org/og-alt.png',
        width: 1800,
        height: 1600,
        alt: 'My custom alt',
      },
    ],
    locale: 'en-US',
    type: 'website',
  },
};

export default function Home() {
  return (
    <>
      <header className="m-6">
        <Image src={logo} alt="" />
      </header>
      <div className="mx-auto my-32 h-full w-full max-w-3xl rounded-xl px-4">
        <h1 className="py-3 text-xl font-bold lowercase antialiased">
          My name is{' '}
          <a href="" className="text-gray-400 hover:underline">
            Eric
          </a>
          , I'm currently living in brazil. My{' '}
          <a href="" className="text-gray-400 hover:underline">
            career
          </a>{' '}
          is being revolved around software engineering world-class
          <a href="" className="text-gray-400 hover:underline">{' '}
            projects
          </a>{' '}
          and pursuing the cutting edge of everything I do. I speak four languages and
          much of my ethos comes from my eagerness to practice novel ways of 'hacking'
          things and learn through constant experimentation.
        </h1>
      </div>
    </>
  );
}
